name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-rust:
    name: Rust Tests
    runs-on: [self-hosted, linux, x64, solana]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup/

      - run: cargo build
      - run: cargo fmt -- --check
      - run: cargo clippy --all-targets -- -D warnings -A clippy::result_large_err
      - run: cargo test

      - uses: ./.github/actions/git-diff/