name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-rust:
    name: Rust Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup/

      - run: cargo build --all-features
      - run: cargo fmt -- --check
      - run: cargo clippy --all-targets -- -D warnings -A clippy::result_large_err
      - run: cargo test

      - uses: ./.github/actions/git-diff/